### ISSUE TITLE
为《Android Gradle 插件中文指南》创建了GitBook

### ISSUE THREAD

**Issue by yourtion** [rujews/android-tech-docs#1]
进行了简单的排版，排版在持续优化中。

在线阅读: http://gradle-guide.books.yourtion.com/

下载电子书: https://www.gitbook.com/book/yourtion/gradle-guide-book/details
- PDF: https://www.gitbook.com/download/pdf/book/yourtion/gradle-guide-book
- EPUB: https://www.gitbook.com/download/epub/book/yourtion/gradle-guide-book
- MOBI: https://www.gitbook.com/download/mobi/book/yourtion/gradle-guide-book

**Comment by flysnoworg** [comment]
Good
