### ISSUE TITLE
-set-debug-mode depends -setup ?

### ISSUE THREAD

**Issue by pleaseyouya** [rujews/android-tech-docs#5]
Hi，在sdk的ant build.xml里面，-set-debug-mode是依赖于-setup的，

```
<target name="-set-debug-mode" depends="-setup">
...
</target>
```

但是看了下，构建Ant脚本这一小节里面，-set-debug-mode却在-setup的前面，

这里是否有问题呢？虽然官方文档确实这样写的，还是有点疑惑，和源码不符。。

**Comment by flysnoworg** [comment]
你这个是ANT构建把，这个是Ant的两个target，没有先后之分的，只要存在就可以依赖的

**Comment by pleaseyouya** [comment]
恩，是的，在Android sdk/tools/ant/build.xml，里面set-debug-mode 依赖于setup
